name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
          buildkitd-config-inline: |
            [registry."10.0.20.100:5000"]
              http = true
              insecure = true

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 10.0.20.100:5000/mcp-unifi-docker:latest